version: "3"

services:
  db:
    image: percona:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dbpassword
  webapp:
    image: "yeasy/simple-web:latest"
    environment:
      DBUSER: root
      DBPASSWORD: dbpassword
    depends_on:
      - db
    ports:
      - "5000:5000"

  webapp2:
    image: "yeasy/simple-web:latest"
    environment:
      DBUSER: root
      DBPASSWORD: dbpassword
    depends_on:
      - db
    ports:
      - "5001:5000"
  nginx:
    image: naga_nginx:latest
    ports:
      - "80:80"
